# Generated by Django 6.0.1 on 2026-01-15 10:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='date',
            field=models.DateField(validators=[api.models.validate_date]),
        ),
    ]
